version = 5.8.0
archive_dir = /etc/letsencrypt/archive/lms-amg.duckdns.org
cert = /etc/letsencrypt/live/lms-amg.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/lms-amg.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/lms-amg.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/lms-amg.duckdns.org/fullchain.pem
[renewalparams]
account = bd17f1e9ef229ef6acd7cfbc2119b0d7
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
lms-amg.duckdns.org = /var/www/certbot
